language: generic
sudo: required
services: 
  - docker
before_install: 
  - "docker build -t betadev07/complex-client:latest -f ./client/Dockerfile.dev ./client"
script: 
  - "docker run -e CI=true betadev07/complex-client npm run test"
after_success: 
  - "docker build -t betadev07/multi-client ./client"
  - "docker build -t betadev07/multi-nginx ./nginx"
  - "docker build -t betadev07/multi-server ./server"
  - "docker build -t betadev07/multi-worker ./worker"
  - "echo \"$DOCKER_PASSWORD\" | docker login -u \"$DOCKER_ID\" --password-stdin"
  - "docker push betadev07/multi-client"
  - "docker push betadev07/multi-nginx"
  - "docker push betadev07/multi-server"
  - "docker push betadev07/multi-worker"
deploy:
  provider: elasticbeanstalk
  app: "multi-docker"
  env: "Multidocker-env-1"
  region: "ap-south-1"
  bucket_name: "elasticbeanstalk-ap-south-1-941450861109"
  bucket_path: "multi-docker"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"

