language: generic
sudo: required
services: 
  - docker
before_install:
  - "docker build -t betadev07/complex-client:latest" -f ./client/Dockerfile.dev ./client 
script:
  - "docker run -e CI=true betadev07/complex-client npm run test"
after_success:
  - "docker build -t betadev07/multi-client ./client"
  - "docker build -t betadev07/multi-nginx ./nginx"
  - "docker build -t betadev07/multi-server ./server"
  - "docker build -t betadev07/multi-worker ./worker"

