version: '3'
services:
  client-server:
    image: "betadev07/client-server"
    hostname: client-server
    restart: always
  backend-server:
    image: "betadev07/multi-server"
    hostname: backend-server
    restart: always
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_PORT=$DB_PORT
      - DATABASE=$DATABASE
      - DB_HOST=$DB_HOST
      - PORT=$PORT
  worker:
    image: "betadev07/client-worker"
    hostname: worker
    environment:
      - REDIS_CLIENT=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "betadev07/multi-nginx"
    hostname: nginx
    restart: always
    ports:
      - "80:80"

